import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from './theme-provider';
import { SideMenu } from '@/components/sideMenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex h-screen flex-col">
            <div className="sticky top-0 flex items-center justify-between border-b-2 border-current p-4">
              <p>Menü</p>
              <SideMenu />
            </div>

            <div className="w-full flex-1 p-4">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
